### ISSUE TITLE
Message Poller

### ISSUE THREAD

**Issue by elia-sysdesign** [redboltz/async_mqtt#109]
Hello,

Sorry for the intrusion.

Just wondering what would be the best way to implement a polling mechanism (after having subscribed to a topic) that would trigger a callback whenever a new message is received.
So far I only found examples that would receive a single message and then disconnect from the broker.
I need to implement an endpoint that would maintain a connection with the broker and that would permanently subscribe to a specific topic and keep receiving messages on said topic.

Thanks in advance.
Elia

**Comment by redboltz** [comment]
You can call the next `recv()` to get meeage().
Here is client_cli.cpp code:
https://github.com/redboltz/async_mqtt/blob/984e81f9c85d21edf88dc2f4548a961748f90eb4/tool/client_cli.cpp#L808-L851

It uses stackless coroutine. If you use callback approach, then call recv() the last part of recv() callback.

NOTE: It is not a **polling**, it is still event driven.

**Comment by redboltz** [comment]
If you still have the problem, feel free to reopen the issue.

**Comment by elia-sysdesign** [comment]
Thank you for the quick response.
I will give it a go and let you know.
