### ISSUE TITLE
Finding async_mqtt, CMake

### ISSUE THREAD

**Issue by rberlich** [redboltz/async_mqtt#135]
Hi there,
there does not seem to be a CMake-macro FindAsyncMQTT.cmake (or similar) that allows searching for the library? Before I try to invent such a macro -- is this an oversight from me?
Kind Regards,
Rüdiger

**Comment by redboltz** [comment]
When you `make install` async_mqtt, then `/usr/local/lib/cmake/async_mqtt_iface/async_mqtt_ifaceConfig.cmake` is generated.
NOTE: `/usr/local/` is default. You can change the location.

Then, you can run your cmake as `async_mqtt_iface_DIR=/usr/local/lib/cmake/ cmake ..`

Your `CMakeLists.txt` should contain `find_package(async_mqtt_iface REQUIRED)`

The point is the library name is `async_mqtt_iface`.
I am not 100% sure but `_iface` seems to be a conventional suffix for header only library, so I added it.

By the way, you can install `async_mqtt` using vcpkg. The command is `vcpkg install async-mqtt`

The project name is `async_mqtt`, cmake library config name is `async_mqtt_iface`, and vcpkg port name is `async-mqtt`.
Sorry for the complex naming, but it is the result that I respect tools mannar.
