### ISSUE TITLE
vcpkg version of library

### ISSUE THREAD

**Issue by decamel** [redboltz/async_mqtt#16]
It would be much easier to install this library from vcpkg manager.

I saw you made it at least once for `mqtt_cpp`

**Comment by redboltz** [comment]
Yes, I'm working on https://github.com/microsoft/vcpkg/pull/31902

**Comment by redboltz** [comment]
The PR for vcpkg that adds async-mqtt port has been merged. In addition, a new PR that updating to version 1.0.3 is accepted.
I guess that you can get async-mqtt via vcpkg when the next vcpkg would be released.
After I confirmed that, then I will close the issue.

**Comment by redboltz** [comment]
vcpkg is still not released but vcpkg master branch already has async-mqtt port. So I close the issue.
