### ISSUE TITLE
install broker

### ISSUE THREAD

**Issue by jbbjarnason** [redboltz/async_mqtt#314]
If I remember correctly, the broker header was part of the public headers of async_mqtt which was quite useful since we could write integration test running a broker and test api between to client implementation in one executable.

Is this planned to be made available as public header or should I just copy the broker implementation?

At least with the most recent version on vcpkg this header was removed.

**Comment by redboltz** [comment]
I proposed async_mqtt to the Boost.Libraries.
async_mqtt can be used for MQTT client and MQTT server (broker).
async_mqtt has tree tools. broker, bench, and client_cli. 
async_mqtt used to have header for broker as public header but for bench and client_cli don't. It was inconsistent.
The header files for broker that was public are too application specific. At least they aren't suitable for boost public header.
So they has been moved to tool directory. They are no longer public header files.
https://github.com/redboltz/async_mqtt/tree/main/tool/include/broker

I am not an expert of vcpkg. If there is some good way to place extra headers to appropriate location (should different place from the publich header) using vcpkg, it is a possible choice.
If there is no good way, please copy or clone repository and add `tool/include` to your include path.

**Comment by jbbjarnason** [comment]
I see two options, 
1. making a cmake option to install tool headers into async_mqtt/tool/... for example and the user would need to add target include path to async_mqtt/tool so the user could include broker/broker.hpp ...

2. Copy code


I would choose option 1 over 2 but it's up to you whether it's okay or not

**Comment by jbbjarnason** [comment]
I could also manually install those headers in vcpkg port file but I don't think it is proper, but it's doable

**Comment by redboltz** [comment]
@jbbjarnason Thank you for providing me with helpful information.
I decided "2. Copy code" is good for me, at least this time.
