### ISSUE TITLE
Send doesn't queue messages and incorrectly reports status of messages.

### ISSUE THREAD

**Issue by magni-mar** [redboltz/async_mqtt#36]
```cpp
// using namespace std;
namespace asio = boost::asio;

class test_class {
private:
  asio::io_context& ctx_;
  std::shared_ptr<async_mqtt::endpoint<async_mqtt::role::client, async_mqtt::protocol::mqtt>> mqtt_client;

public:
  test_class(asio::io_context& ctx)
      : ctx_(ctx), mqtt_client(std::make_shared<async_mqtt::endpoint<async_mqtt::role::client, async_mqtt::protocol::mqtt>>(
                       async_mqtt::protocol_version::v3_1_1,
                       ctx_.get_executor())) {
    asio::co_spawn(mqtt_client->strand(), test_func(), asio::detached);
  }

  auto test_func() -> asio::awaitable<void> {
    asio::ip::tcp::socket resolve_sock{ ctx_ };
    asio::ip::tcp::resolver res{ resolve_sock.get_executor() };
    asio::ip::tcp::resolver::results_type resolved_ip = co_await res.async_resolve("localhost", "1883", asio::use_awaitable);

    try {
      asio::ip::tcp::endpoint endpoint =
          co_await asio::async_connect(mqtt_client->next_layer(), resolved_ip, asio::use_awaitable);

      std::cout << endpoint.address().to_string() << '\n';
    } catch (const std::exception& e) {
      std::cout << "Exception during connect: " << e.what() << '\n';
    } catch (...) {
      std::cout << "Unknown exception during connect\n";
    }

    co_await mqtt_client->send(
        async_mqtt::v3_1_1::connect_packet{ true, 0x1234, async_mqtt::allocate_buffer("cid1"), async_mqtt::nullopt,
                                            async_mqtt::nullopt, async_mqtt::nullopt },
        asio::use_awaitable);

    async_mqtt::packet_variant packet_variant = co_await mqtt_client->recv(asio::use_awaitable);

    co_await mqtt_client->send(
        async_mqtt::v3_1_1::publish_packet{ mqtt_client->acquire_unique_packet_id().value(),
                                            async_mqtt::allocate_buffer("test_topic"),
                                            async_mqtt::allocate_buffer("test_payload"), async_mqtt::qos::at_least_once },
        asio::use_awaitable);

    std::string payload = "n";
    while (true) {
      std::cout << "Sending payload: " << payload << "\n";
      auto result = co_await mqtt_client->send(
          async_mqtt::v3_1_1::publish_packet{ mqtt_client->acquire_unique_packet_id().value(),
                                              async_mqtt::allocate_buffer("test_topic"),
                                              async_mqtt::allocate_buffer(payload), async_mqtt::qos::at_least_once },
          asio::use_awaitable);

      if (!result) {
        std::cout << "Successfully sent payload\n";
      } else {
        std::cout << "Failed to send payload\n";
      }

      asio::steady_timer timer{ ctx_, std::chrono::seconds{ 3 } };
      co_await timer.async_wait(asio::use_awaitable);
      payload += "n";
    }
    co_return;
  }

};

auto main() -> int {
  asio::io_context ctx{};
  test_class tester(ctx);
  ctx.run();
  return 0;
}
```

```
[2023-06-27 12:09:21.979104] [0x00007fb47e4de780] [info]    send:v3_1_1::connect{cid:cid1,ka:4660,cs:true}
[2023-06-27 12:09:21.979115] [0x00007fb47e4de780] [info]    [store] clear
[2023-06-27 12:09:21.979142] [0x00007fb47e4de780] [info]    recv
[2023-06-27 12:09:21.979174] [0x00007fb47e4de780] [info]    recv:v3_1_1::connack{rc:accepted,sp:false}
[2023-06-27 12:09:21.979178] [0x00007fb47e4de780] [info]    [store] clear
[2023-06-27 12:09:21.979181] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:1
[2023-06-27 12:09:21.979186] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:1}
Sending payload: n
[2023-06-27 12:09:21.979202] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:2
[2023-06-27 12:09:21.979204] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:2}
Successfully sent payload
Sending payload: nn
[2023-06-27 12:09:24.979298] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:3
[2023-06-27 12:09:24.979318] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:3}
Successfully sent payload
Sending payload: nnn
[2023-06-27 12:09:27.979727] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:4
[2023-06-27 12:09:27.979746] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:4}
Successfully sent payload
Sending payload: nnnn
[2023-06-27 12:09:30.980130] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:5
[2023-06-27 12:09:30.980148] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:5}
Successfully sent payload
Sending payload: nnnnn
[2023-06-27 12:09:33.980610] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:6
[2023-06-27 12:09:33.980627] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:6}
[2023-06-27 12:09:33.980655] [0x00007fb47e4de780] [info]    send error:Broken pipe
Failed to send payload
Sending payload: nnnnnn
[2023-06-27 12:09:36.980985] [0x00007fb47e4de780] [info]    acquire_unique_packet_id:7
[2023-06-27 12:09:36.981003] [0x00007fb47e4de780] [info]    send:v3_1_1::publish{topic:test_topic,qos:at_least_once,retain:no,dup:no,pid:7}
```

![image](https://github.com/redboltz/async_mqtt/assets/135731785/2b53105c-97c3-4aae-9425-872282b9f63d)

I encountered this error while working in a larger project but tried to isolate it to the minimum viable example.

In order to test this I am sending a new payload with an added "n" every 3 seconds. The first three arrive succcessfully at the MQTT broker. This is when I turn off the MQTT broker. When this happens the next one reports as being successfully sent (this is incorrect), but all subsequent messages report as being unsuccessfully sent. 

Perhaps I am using the library incorrectly but if so, I would like to know where I am incorrect. In a larger codebase I have slightly different code which tries to as forcefully as possible to send the subsequent messages. When this happens the new messages are sent but the missing ones are left out. This would be equivalent to, in this example, to the MQTT broker receiveing:

["n", "nn", "nnn", "nnnnn", "nnnnnn"].

Leaving out the messages when the broker was down.

**Comment by redboltz** [comment]
The CompletionToken of send() reflects Boost.Asio async_write() result. I guess that the PUBLISH packet that has the payload "nnn"  is successfully written to the socket but the broker doesn't receive it because of turing off.
So the success CompletionToken result of send() function doesn't mean the message is received by the broker.
If you want to know the message "nnn" is received by the broker (or not), you need to check PUBACK packet.
You can get the packet_id that is passed to the PUBLISH packet as follows:

```cpp
auto packet_id = mqtt_client->acquire_unique_packet_id().value();
```

And you can check PUBACK packet from received `packet_variant`.

**Comment by magni-mar** [comment]
Thank you for the quick response. I am trying to achieve what you are talking about using the following code:

```
      auto packet_id = mqtt_client->acquire_unique_packet_id().value();

      auto result = co_await mqtt_client->send(
          async_mqtt::v3_1_1::publish_packet{ packet_id, async_mqtt::allocate_buffer("test_topic"),
                                              async_mqtt::allocate_buffer(payload), async_mqtt::qos::at_least_once },
          asio::use_awaitable);

      async_mqtt::packet_variant pv = co_await mqtt_client->recv(asio::use_awaitable);
      std::cout << "result: " << pv.get<async_mqtt::v3_1_1::puback_packet>().packet_id() << " and packet_id: " << packet_id
                << "\n";
```

but it always gives me the following:

```
result: 2 and packet_id: 1
result: 1 and packet_id: 2
result: 2 and packet_id: 1
```

**Comment by redboltz** [comment]
Ah, it is due to packet_id  management mechanism.
After PUBACK packet is received but before recv() CompletionToken is invoked, the packet_id becomes reusable.
So the next `acquire_unique_packet_id().value()` returns the minimum value of usable packet_id set.

If you really want to know which PUBLISH packet is not acnoledged, then you need to prepare checking mechanism.

For example `std::map<packet_id_t, value_type>`.
value_type could be payload or whole `async_mqtt::v3_1_1::publish_packet{}`.
When sending PUBLISH, insert the entry.
When PUBACK is received, then erase the element.

Finally, unacknoledged entries are remained in the map.

By the way, if your goal is simply resending unacknoledged packet, easier solution exists.
It is achieved by MQTT session management mechanism.

Simply, set `clean_session` flag to false on the CONNECT packet. 
After send it, broker returns CONNACK packet with session_present is false because there is no session in the broker for the first time.
Let's say close and reconnect happens
The client connect again with `clean_session` false, then broker should return CONNACK packet with `session_present` true.
In this case, async_mqtt automatically sends unacknoledged PUBLISH packet.

**Comment by magni-mar** [comment]
My goal is to resend unacknowledged packages so I will attempt the solution of setting clean_session to false. This function attempts to send the message:

```cpp

  template <class value_type>
  auto send_message([[maybe_unused]] std::expected<value_type, std::error_code> msg,
                    std::string value_string,
                    std::string signal_name) -> asio::awaitable<void> {
    while (true) {
      co_await asio::post(mqtt_client_->strand(), asio::use_awaitable);

      if (msg) {
        logger_.trace("sending message: {} to topic: {}", value_string, signal_name);

        try {
          auto result = co_await mqtt_client_->send(
              async_mqtt::v3_1_1::publish_packet{
                  mqtt_client_->acquire_unique_packet_id().value(), async_mqtt::allocate_buffer(signal_name),
                  async_mqtt::allocate_buffer(value_string), async_mqtt::qos::at_least_once },
              asio::use_awaitable);

          // TODO: after broker goes down the next message seems to be successful, need some sort of ack confirmation from

          logger_.trace(result.message());

          if (result) {
            logger_.error("failed to connect to mqtt client: {}", result.message());
            // co_await mqtt_client_->close(boost::asio::use_awaitable);
            co_await asio::steady_timer{ ctx_, std::chrono::milliseconds{ 100 } }.async_wait(asio::use_awaitable);
            co_await mqtt_connect();
            // sleep for 100 milliseconds

          } else {
            logger_.trace("message sent successfully");
            break;
          }
        } catch (std::exception& e) {
          logger_.error("exception in send: {}", e.what());
        }
      }
    }
    co_return;
  }

```

if it fails this function is called:

```cpp

  auto mqtt_connect() -> asio::awaitable<void> {
    logger_.trace("Connecting to MQTT broker: {}:{}", mqtt_host_, mqtt_port_);
    while (true) {
      try {
        asio::ip::tcp::socket resolve_sock{ ctx_ };
        asio::ip::tcp::resolver res{ resolve_sock.get_executor() };
        asio::ip::tcp::resolver::results_type resolved_ip =
            co_await res.async_resolve(mqtt_host_, mqtt_port_, asio::use_awaitable);

        [[maybe_unused]] asio::ip::tcp::endpoint endpoint =
            co_await asio::async_connect(mqtt_client_->next_layer(), resolved_ip, asio::use_awaitable);

        co_await mqtt_client_->send(
            async_mqtt::v3_1_1::connect_packet{ false, 0x1234, async_mqtt::allocate_buffer("cid1"), async_mqtt::nullopt,
                                                async_mqtt::nullopt, async_mqtt::nullopt },
            asio::use_awaitable);

        async_mqtt::packet_variant packet_variant = co_await mqtt_client_->recv(asio::use_awaitable);

        co_await mqtt_client_->send(async_mqtt::v3_1_1::publish_packet{ mqtt_client_->acquire_unique_packet_id().value(),
                                                                        async_mqtt::allocate_buffer("test_topic"),
                                                                        async_mqtt::allocate_buffer("test_payload"),
                                                                        async_mqtt::qos::at_least_once },
                                    asio::use_awaitable);

        logger_.trace("MQTT connection successful");
        break;
      } catch (std::exception& e) {
        logger_.log<tfc::logger::lvl_e::error>("exception in mqtt_connect: {}", e.what());
      }
      logger_.trace("retrying mqtt connection");
      co_await asio::steady_timer{ ctx_, std::chrono::milliseconds(100) }.async_wait(asio::use_awaitable);
    }
  }

```

However, the same problem persists. If I send "false" to a topic it will tell me that it has been sent.

```
*** trace [13:30:09 +00:00] (thread 34968) def.mqtt_broadcaster ***              sending message: false to topic: tfcctl/def/bool/bool3/test 
*** trace [13:30:09 +00:00] (thread 34968) def.mqtt_broadcaster ***              Success 
*** trace [13:30:09 +00:00] (thread 34968) def.mqtt_broadcaster ***              message sent successfully 
```

but MQTT explorer will tell me that the latest message was false. Yet, I have set clean_session to false.

![image](https://github.com/redboltz/async_mqtt/assets/135731785/02ff8d9a-53a7-4bfb-9a0e-12918ee51aa2)

**Comment by redboltz** [comment]
Another hint:
In order to analyse the problem is at the client side or the broker side, using https://github.com/redboltz/async_mqtt/blob/doc/README.md async_mqtt broker instead of yours.

**Comment by redboltz** [comment]
I just noticed that one more point.

> but it always gives me the following:
> 
> ```
> result: 2 and packet_id: 1
> result: 1 and packet_id: 2
> result: 2 and packet_id: 1
> ```

If you send only 3 PUBLISH packets their paylaod "n", "nn", and "nnn", and then you got the log above, this indicates that the broker receives 3 packets including "nnn". Because the broker sent PUBACK packet after received PUBLISH (QoS1) packet, and the client receives 3 PUBACK packets.

**Comment by redboltz** [comment]
async_mqtt doesn't provide reconnect functionalty, because MQTT doesn't define RECONNECT explicitly.
How do we reconnect?
Simply do the connect sequence again. If you want to send the same CONNECT packet again, you can store the first CONNECT packet to somewhare and use it on the second CONNECT packet sending.

async_mqtt's broker doesn't support persistent. So if you kill the broker process, then all information stored in the broker would be lost.
If you want to simulate disconnect between the client and the broker, you can use socat command.
https://linux.die.net/man/1/socat

**Comment by magni-mar** [comment]
Hi @redboltz , my team and I have figured out a solution to our problem. 

To start with the reconnect mechanism worked as you implied, by sending a connect packet again with clean_session set to false each time.

With regards to the buffering problem, the solution was to set Session Expiry Interval to a value with the line

```cpp
async_mqtt::property::session_expiry_interval{10000}
```

added to the connect call because otherwise it defaults to 0 which was causing the broker to close the session each time the client disconnected. 

Thank you for quick responses and a pleasant exchange.

**Comment by magni-mar** [comment]
Hi @redboltz , my team and I have figured out a solution to our problem. 

To start with the reconnect mechanism worked as you implied, by sending a connect packet again with clean_session set to false each time.

With regards to the buffering problem, the solution was to set Session Expiry Interval to a value with the line

```cpp
async_mqtt::property::session_expiry_interval{10000}
```

added to the connect call because otherwise it defaults to 0 which was causing the broker to close the session each time the client disconnected. 

Thank you for quick responses and a pleasant exchange.

**Comment by redboltz** [comment]
You are welcome. Just a question, are you using MQTT v5? Your example code is MQTT v3.1.1 so I assumed that you are using MQTT v3.1.1.
`property` is MQTT v5 feature, and SessionExpiryInterval is one of the property.

async_mqtt is designed working well both MQTT v5 and v3.1.1. If you are using MQTT v3.1.1, then session should be preserved without SessionExpiryInterval by the broker. So asnyc_mqtt should work as you expected without SessionExpiryInterval setting as long as you are using MQTT v3.1.1.
If it doesn't, it could be an async_mqtt bug.

**Comment by magni-mar** [comment]
Initially, we were using v3.1.1 but decided to pivot to v5 and then the issue got resolved. I am unsure weather the queueing mechanism in v3.1.1 is an error in the library or was something else on our side.

**Comment by redboltz** [comment]
Thank you for the comment :)
