### ISSUE TITLE
Reason codes

### ISSUE THREAD

**Issue by magni-mar** [redboltz/async_mqtt#72]
I was working with std::error_codes and reason codes in my application and came across something interesting which might be a good addition to this library. It is possible to define async_mqtt reason codes as std::error_codes in order to make them more accessible.

Example

```cpp
namespace detail {

class suback_error_category : public std::error_category {
public:
  virtual const char* name() const noexcept override { return "async_mqtt::suback_error_category"; }
  virtual std::string message(int value) const override {
    return suback_reason_code_to_str(static_cast<suback_reason_code>(value));
  }
};

}  // namespace detail

const std::error_category& suback_error_category() {
  static detail::suback_error_category instance;
  return instance;
}

inline std::error_code make_error_code(suback_reason_code v) {
  return std::error_code(static_cast<uint8_t>(v), async_mqtt::suback_error_category());
}
```

This is just for suback_reason_code to give you the idea. Using this I can call:

```cpp
    for (auto const& entry : suback_packet.entries()) {
      if (entry != async_mqtt::suback_reason_code::granted_qos_0) {
        logger_.error("Error subscribing to topic: {}, reason code: {}", ncmd_topic,
                      async_mqtt::suback_reason_code_to_str(entry));
        co_return async_mqtt::make_error_code(entry);
      }
    }
```

and get a std::error_code from the async_mqtt reason codes. Do you like this? I can write for other reason codes and PR if you'd like.

**Comment by redboltz** [comment]
Now, return_code (v3.1.1) and reason_code (v5) are defined as follows:

MQTT v3.1.1
https://github.com/redboltz/async_mqtt/blob/main/include/async_mqtt/packet/connect_return_code.hpp
https://github.com/redboltz/async_mqtt/blob/main/include/async_mqtt/packet/suback_return_code.hpp

MQTT v5
https://github.com/redboltz/async_mqtt/blob/main/include/async_mqtt/packet/reason_code.hpp

They are a part of MQTT spec like as PacketIdentifier, ClientIdentifier, TopicFilter...
So I personally think that the current implementation is enough.

I understand that your application requires `std::error_code` based integration.
However, I guess that not many users require it.
So far, my priority is keep the library code small and simple (including test code to keep high coverage). 

Please keep your converter code as your application or your common adaptor library code.

If many people require the same functionality, I would re-consider.
Anyway, thank you for proposing.

**Comment by redboltz** [comment]
@magni-mar , thank you for understanding. 
I guessed it from your thumbs up emoticon.

I close the issue once.
