### ISSUE TITLE
Build error: "use of deleted function"

### ISSUE THREAD

**Issue by benjacam** [redboltz/async_mqtt#86]
Hello,
Thank you for writing this async_mqtt, it looks great!
I'm trying to build version 2.0.0 with GCC 9.3.0. I'm cross-compiling using arm-oe-linux-gnueabi-g++.

The build is failing right from the start:

`
/arm-oe-linux-gnueabi-g++ --sysroot=/home/bjc/quectel_sensor_sdk/rm520nglaar/ql-ol-extsdk/ql-sysroots -DASYNC_MQTT_USE_TLS -Iasync_mqtt-2.0.0/include -isystem /home/bjc/quectel_sensor_sdk/boost_1_81_0 -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -Os -DNDEBUG -std=c++2a -MD -MT example/CMakeFiles/ep_cb_mqtt_client.dir/ep_cb_mqtt_client.cpp.o -MF CMakeFiles/ep_cb_mqtt_client.dir/ep_cb_mqtt_client.cpp.o.d -o CMakeFiles/ep_cb_mqtt_client.dir/ep_cb_mqtt_client.cpp.o -c async_mqtt-2.0.0/example/ep_cb_mqtt_client.cpp
In file included from async_mqtt-2.0.0/include/async_mqtt/packet/property_variant.hpp:11,
                 from async_mqtt-2.0.0/include/async_mqtt/packet/will.hpp:12,
                 from async_mqtt-2.0.0/include/async_mqtt/packet/v3_1_1_connect.hpp:26,
                 from async_mqtt-2.0.0/include/async_mqtt/packet/packet_variant.hpp:11,
                 from async_mqtt-2.0.0/include/async_mqtt/buffer_to_packet_variant.hpp:12,
                 from async_mqtt-2.0.0/include/async_mqtt/all.hpp:11,
                 from async_mqtt-2.0.0/example/ep_cb_mqtt_client.cpp:12:
async_mqtt-2.0.0/include/async_mqtt/packet/property.hpp: In constructor ‘async_mqtt::property::detail::binary_property::binary_property(async_mqtt::property::id, async_mqtt::buffer)’:
async_mqtt-2.0.0/include/async_mqtt/packet/property.hpp:142:19: error: use of deleted function ‘async_mqtt::buffer::buffer(const async_mqtt::buffer&)’
  142 |          length_(2) // size 2
      |                   ^
In file included from async_mqtt-2.0.0/include/async_mqtt/all.hpp:10,
                 from async_mqtt-2.0.0/example/ep_cb_mqtt_client.cpp:12:
async_mqtt-2.0.0/include/async_mqtt/buffer.hpp:48:5: note: ‘async_mqtt::buffer::buffer(const async_mqtt::buffer&) noexcept’ is implicitly deleted because its exception-specification does not match the implicit exception-specification ‘’
   48 |     buffer(buffer const& other) noexcept = default;
      |     ^~~~~~
`

**Comment by redboltz** [comment]
Thanks for reporting the issue. It should be fixed by #87 . Please try it.

**Comment by benjacam** [comment]
Dear @redboltz , thank you - I can now build the ep_future_mqtt_client.
